#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kguiaddons
Version  : 5.48.0
Release  : 1
URL      : https://download.kde.org/stable/frameworks/5.48/kguiaddons-5.48.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.48/kguiaddons-5.48.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: kguiaddons-lib
Requires: kguiaddons-license
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde

%description
# KDE GUI Addons
Utilities for graphical user interfaces
## Introduction
The KDE GUI addons provide utilities for graphical user interfaces in the areas
of colors, fonts, text, images, keyboard input.

%package dev
Summary: dev components for the kguiaddons package.
Group: Development
Requires: kguiaddons-lib
Provides: kguiaddons-devel

%description dev
dev components for the kguiaddons package.


%package lib
Summary: lib components for the kguiaddons package.
Group: Libraries
Requires: kguiaddons-license

%description lib
lib components for the kguiaddons package.


%package license
Summary: license components for the kguiaddons package.
Group: Default

%description license
license components for the kguiaddons package.


%prep
%setup -q -n kguiaddons-5.48.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531949326
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1531949326
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kguiaddons
cp COPYING %{buildroot}/usr/share/doc/kguiaddons/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/kguiaddons/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KGuiAddons/KColorCollection
/usr/include/KF5/KGuiAddons/KColorMimeData
/usr/include/KF5/KGuiAddons/KColorUtils
/usr/include/KF5/KGuiAddons/KDateValidator
/usr/include/KF5/KGuiAddons/KFontUtils
/usr/include/KF5/KGuiAddons/KIconUtils
/usr/include/KF5/KGuiAddons/KImageCache
/usr/include/KF5/KGuiAddons/KModifierKeyInfo
/usr/include/KF5/KGuiAddons/KWordWrap
/usr/include/KF5/KGuiAddons/kcolorcollection.h
/usr/include/KF5/KGuiAddons/kcolormimedata.h
/usr/include/KF5/KGuiAddons/kcolorutils.h
/usr/include/KF5/KGuiAddons/kdatevalidator.h
/usr/include/KF5/KGuiAddons/kfontutils.h
/usr/include/KF5/KGuiAddons/kguiaddons_export.h
/usr/include/KF5/KGuiAddons/kiconutils.h
/usr/include/KF5/KGuiAddons/kimagecache.h
/usr/include/KF5/KGuiAddons/klocalimagecacheimpl.h
/usr/include/KF5/KGuiAddons/kmodifierkeyinfo.h
/usr/include/KF5/KGuiAddons/kwordwrap.h
/usr/include/KF5/kguiaddons_version.h
/usr/lib64/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake
/usr/lib64/cmake/KF5GuiAddons/KF5GuiAddonsConfigVersion.cmake
/usr/lib64/cmake/KF5GuiAddons/KF5GuiAddonsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5GuiAddons/KF5GuiAddonsTargets.cmake
/usr/lib64/libKF5GuiAddons.so
/usr/lib64/qt5/mkspecs/modules/qt_KGuiAddons.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5GuiAddons.so.5
/usr/lib64/libKF5GuiAddons.so.5.48.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/kguiaddons/COPYING
/usr/share/doc/kguiaddons/COPYING.LIB
